import { readFileSync } from 'fs';
const base = 'C:/Users/Administrator/.qclaw/workspace-agent-7ac59ebd/chat-app-workers/';
const html = readFileSync(base + '_live_now.html', 'utf16le');
console.log('Length:', html.length);
console.log('First 500:', JSON.stringify(html.substring(0, 500)));
console.log('\nLast 500:', JSON.stringify(html.substring(html.length - 500)));
console.log('\nHas Cloudflare:', html.includes('Cloudflare'));
console.log('Has challenge:', html.includes('challenge'));
console.log('Has ray ID:', html.includes('Ray ID'));
console.log('Has DDoS:', html.includes('DDoS'));
console.log('Has verifying:', html.includes('verifying'));
console.log('Has /cdn-cgi:', html.includes('/cdn-cgi/'));
