import { readFileSync, writeFileSync } from 'fs';
import { pathToFileURL } from 'url';

const base = 'C:/Users/Administrator/.qclaw/workspace-agent-7ac59ebd/chat-app-workers/';

// 1. Import html_src.js (fixed) to get template VALUES
const htmlSrc = readFileSync(base + 'src/html_src.js', 'utf8');
const mod = await import('data:text/javascript;base64,' + Buffer.from(htmlSrc).toString('base64'));
const HTML = mod.HTML, ADMIN_HTML = mod.ADMIN_HTML, TEST_HTML = mod.TEST_HTML,
        ABOUT_HTML = mod.ABOUT_HTML, PRICING_HTML = mod.PRICING_HTML;
console.log('Template values:');
for (const [k, v] of [['HTML', HTML], ['ADMIN_HTML', ADMIN_HTML], ['TEST_HTML', TEST_HTML], ['ABOUT_HTML', ABOUT_HTML], ['PRICING_HTML', PRICING_HTML]]) {
  console.log(' ', k, v.length, 'chars, </script>:', v.includes('</script>'), '</html>:', v.includes('</html>'));
}

// 2. Read index_src.js, remove import lines
let index = readFileSync(base + 'src/index_src.js', 'utf8');
index = index.replace(/^import[^\n]*\n/gm, '');

// 3. Read wechat_src.js, strip export keywords
let wechat = readFileSync(base + 'src/wechat_src.js', 'utf8');
wechat = wechat.replace(/export\s+(async\s+)?function\s+/g, '$1function ');
// Check no remaining exports/imports
if (/^\s*(export|import)\b/m.test(wechat)) {
  const m = wechat.match(/^\s*(export|import)\b.*$/m);
  console.log('WARN: remaining import/export in wechat:', m && m[0]);
}

// Check index for remaining import/export besides export default/class
const idxExports = index.match(/^export\s+.*$/gm);
console.log('index exports:', JSON.stringify(idxExports));

// 4. Build final bundle
const parts = [];
parts.push('// ugochat - Cloudflare Workers + Durable Objects (bundled)');
parts.push('// Generated by build_final.mjs - do not edit directly');
parts.push('');
parts.push('const HTML = ' + JSON.stringify(HTML) + ';');
parts.push('const ADMIN_HTML = ' + JSON.stringify(ADMIN_HTML) + ';');
parts.push('const TEST_HTML = ' + JSON.stringify(TEST_HTML) + ';');
parts.push('const ABOUT_HTML = ' + JSON.stringify(ABOUT_HTML) + ';');
parts.push('const PRICING_HTML = ' + JSON.stringify(PRICING_HTML) + ';');
parts.push('');
parts.push('// ---- WeChat Pay helpers ----');
parts.push(wechat.trim());
parts.push('');
parts.push('// alias imports used by main code');
parts.push('const wxConfigured = isConfigured;');
parts.push('const wxCtx = buildCtx;');
parts.push('const wxOrder = wechatUnifiedOrder;');
parts.push('const wxDecrypt = decryptResource;');
parts.push('const wxVerify = verifyNotify;');
parts.push('');
parts.push('// ---- Main worker ----');
parts.push(index.trim());
parts.push('');

const bundle = parts.join('\n');
writeFileSync(base + 'dist/index.js', bundle, 'utf8');
console.log('Bundle written:', bundle.length, 'bytes');

// 5. Validate
import { execSync } from 'child_process';
writeFileSync(base + 'dist/_check.mjs', bundle, 'utf8');
try {
  execSync('node --check "' + base + 'dist/_check.mjs"', { stdio: 'pipe' });
  console.log('node --check: PASS');
} catch (e) {
  console.log('node --check: FAIL');
  console.log(e.stderr ? e.stderr.toString() : e.message);
  process.exit(1);
}
