name = "tinychat"
main = "dist/index.js"
compatibility_date = "2026-07-21"

[[durable_objects.bindings]]
name = "CHAT"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]
