import { readFileSync } from 'fs';
const h = readFileSync('src/html.js', 'utf8');
console.log('html.js size:', h.length);
console.log('export default HTML:', h.includes('export default HTML'));
console.log('ADMIN_HTML:', h.includes('const ADMIN_HTML'));
console.log('TEST_HTML:', h.includes('const TEST_HTML'));
console.log('ABOUT_HTML:', h.includes('const ABOUT_HTML'));
console.log('PRICING_HTML:', h.includes('const PRICING_HTML'));
console.log('doBuy:', h.includes('function doBuy'));
console.log('confirmPaid:', h.includes('confirmPaid'));
console.log('uploadQR:', h.includes('uploadQR'));
console.log('loadPending:', h.includes('loadPending'));
console.log('approvePay:', h.includes('approvePay'));
console.log('doLogin:', h.includes('function doLogin'));
console.log('Plain </script>:', (h.match(/<\/script>/g)||[]).length);
console.log('CRLF count:', (h.match(/\r\n/g)||[]).length);
console.log('LF count:', (h.match(/\n/g)||[]).length);
const w = readFileSync('src/wechat.js', 'utf8');
console.log('\nwechat.js size:', w.length);
console.log('wxConfigured:', w.includes('wxConfigured'));
console.log('wxOrder:', w.includes('wechatUnifiedOrder'));
console.log('wxDecrypt:', w.includes('decryptResource'));
